FROM node:20-alpine AS deps
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate
WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/info/package.json ./apps/info/
RUN pnpm install --frozen-lockfile --filter info

FROM deps AS builder
COPY apps/info ./apps/info
WORKDIR /app/apps/info
ARG QUIZ_URL
ENV VITE_QUIZ_URL=${QUIZ_URL}
RUN pnpm build

FROM nginx:1.27-alpine AS runner
COPY --from=builder /app/apps/info/dist /usr/share/nginx/html
